### ISSUE TITLE
Compiler error after upgrade from v0.18.7 to v0.18.8: type mismatch error for fuego.Get

### ISSUE THREAD

**Issue by fieneeckstein** [go-fuego/fuego#502]
**To Reproduce**

1. Clone the hello-world example project with fuego v0.18.8
2. run go mod tidy

**Expected behavior**
 The helloWorld function should be successfully registered as a handler for the GET route /.

**Actual behavior**
The compiler throws a type mismatch error because the helloWorld function signature does not match the expected handler type for fuego.Get.

**Screenshots**

![Image](https://github.com/user-attachments/assets/9608fc05-fb99-4be9-b700-cf99e5f7aa0d)

**Framework version (please check if it happens with the last
Fuego version before posting):**
v.0.18.8

**Go version (please check if it happens with the last Go version before posting):**
go1.24.2 darwin/amd64

**Additional context**
IntelliJ IDEA 2025.1 (Ultimate Edition)

**Comment by EwenQuim** [comment]
Works for me 🤔 

Are you sure that
- you're using go1.24
- you're using fuego 0.18.8
- you restarted your IDE ?

<img width="458" alt="Image" src="https://github.com/user-attachments/assets/cadba424-4530-428c-bd4c-cbf2ec573f18" />

<img width="588" alt="Image" src="https://github.com/user-attachments/assets/798e9c78-b902-4b98-8eed-4f56cf7cc846" />

**Comment by EwenQuim** [comment]
Also, it obviously still build our internal apps (we test it before releasing new versions).

So this shouldn't be a breaking change.

Maybe I'm missing something, in this case please be more precise and send some more indicators!

**Comment by EwenQuim** [comment]
Ahh I forgot : you might want to use `go mod tidy` even after `go get -u github.com/go-fuego/fuego` to clean your lockfile 😉

**Comment by fieneeckstein** [comment]
Thanks for your help. I double checked the go and fuego versions. This error occurs for me with fuego v0.18.8, but disappears when I switch to v0.18.7. I checked again for any IntelliJ or plugin updates, but I am up to date. I tried your idea to clean the lockfile, but also no luck. But you are correct, the project still builds so maybe it's more likely an IDE/golang plugin issue?

**Comment by EwenQuim** [comment]
Ok so the project builds with v0.18.8 but with IDE errors, and with 0.18.7 there are no errors at all?

**Comment by fieneeckstein** [comment]
correct

**Comment by EwenQuim** [comment]
Ok so I guess that's just some IDE issue.

Fuego being simply a library, I'm afraid there's nothing we can do here :/

**Comment by fieneeckstein** [comment]
thanks anyway! 👍

**Comment by mike-kramer** [comment]
Also have this error in goland. It's because early ContextNoBody was ContextWithBody[any], and now it's

```go
type (
	// ContextNoBody is the context of the request with no body and no typed parameters.
	// It contains the path parameters, and the HTTP request.
	ContextNoBody = Context[any, any]

	// ContextWithBody is the context of the request with typed body and no typed parameters.
	// It contains the request body, the path parameters, the query parameters, and the HTTP request.
	// Please do not use a pointer type as parameters.
	ContextWithBody[B any] = Context[B, any]

	// ContextWithParams is the context of the request with no body and typed parameters.
	// It contains the path parameters, the query parameters, and the HTTP request.
	// Please do not use a pointer type as parameters.
	ContextWithParams[P any] = Context[any, P]
)
```

The compiler understands it, but IDE doesn't

**Comment by Simplyauf** [comment]
I can get this fixed for you asap

**Comment by EwenQuim** [comment]
Is it fixed now?

**Comment by evangrayson** [comment]
@EwenQuim It looks like this issue isn't fixed. The problem seems to be related to the type aliasing here: https://github.com/go-fuego/fuego/blob/main/ctx.go#L23-L37 I suspect it might be an IntelliJ-specific issue, possibly struggling with cyclic types.

**Comment by mike-kramer** [comment]
Fixed in GoLand 2025.2.2
